spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:h2:mem:encurtador
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update